name: Hardik Nanda
description: Blogging about InfoSec related stuff
meta_description: "Blogging about InfoSec related stuff"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 40
baseurl: /
domain_name: "https://r0075h3ll.github.io"
#google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "r0075h3ll"
author: "Hardik Nanda"

# Disqus config
disqus-shortname: ""
